Traceback (most recent call last):
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
filename = 'zero_N1.fits'
master_bias = CCDData.read(directory+filename)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-5-b47259b7e49d>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mfilename[0m [0;34m=[0m [0;34m'zero_N1.fits'[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mmaster_bias[0m [0;34m=[0m [0mCCDData[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mdirectory[0m[0;34m+[0m[0mfilename[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/nddata/mixins/ndio.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
[1;32m     56[0m [0;34m[0m[0m
[1;32m     57[0m     [0;32mdef[0m [0m__call__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 58[0;31m         [0;32mreturn[0m [0mregistry[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_cls[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     59[0m [0;34m[0m[0m
[1;32m     60[0m [0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/registry.py[0m in [0;36mread[0;34m(cls, format, cache, *args, **kwargs)[0m
[1;32m    503[0m                     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    504[0m                         [0mctx[0m [0;34m=[0m [0mget_readable_fileobj[0m[0;34m([0m[0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0;34m'binary'[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0mcache[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 505[0;31m                         [0mfileobj[0m [0;34m=[0m [0mctx[0m[0;34m.[0m[0m__enter__[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    506[0m                     [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    507[0m                         [0;32mraise[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib64/python3.8/contextlib.py[0m in [0;36m__enter__[0;34m(self)[0m
[1;32m    111[0m         [0;32mdel[0m [0mself[0m[0;34m.[0m[0margs[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mkwds[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mfunc[0m[0;34m[0m[0;34m[0m[0m
[1;32m    112[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 113[0;31m             [0;32mreturn[0m [0mnext[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mgen[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    114[0m         [0;32mexcept[0m [0mStopIteration[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    115[0m             [0;32mraise[0m [0mRuntimeError[0m[0;34m([0m[0;34m"generator didn't yield"[0m[0;34m)[0m [0;32mfrom[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/utils/data.py[0m in [0;36mget_readable_fileobj[0;34m(name_or_obj, encoding, cache, show_progress, remote_timeout, sources, http_headers)[0m
[1;32m    250[0m                 [0mtimeout[0m[0;34m=[0m[0mremote_timeout[0m[0;34m,[0m [0msources[0m[0;34m=[0m[0msources[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    251[0m                 http_headers=http_headers)
[0;32m--> 252[0;31m         [0mfileobj[0m [0;34m=[0m [0mio[0m[0;34m.[0m[0mFileIO[0m[0;34m([0m[0mname_or_obj[0m[0;34m,[0m [0;34m'r'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    253[0m         [0;32mif[0m [0mis_url[0m [0;32mand[0m [0;32mnot[0m [0mcache[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    254[0m             [0mdelete_fds[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mfileobj[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/jzamorano/Desktop/NOT_2008/N1/zero_N1.fits'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jzamorano/Desktop/NOT_2008/N1/zero_N1.fits'

