Traceback (most recent call last):
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
keys = ['imagetyp','OBJECT' , 'EXPTIME' , 'ALFLTID' , 'FAFLTID' , 'FBFLTID']
ic1 = ImageFileCollection(directory, keywords=keys) # only keep track of keys
ic1.summary.colnames
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-7-729ccda437e4>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mkeys[0m [0;34m=[0m [0;34m[[0m[0;34m'imagetyp'[0m[0;34m,[0m[0;34m'OBJECT'[0m [0;34m,[0m [0;34m'EXPTIME'[0m [0;34m,[0m [0;34m'ALFLTID'[0m [0;34m,[0m [0;34m'FAFLTID'[0m [0;34m,[0m [0;34m'FBFLTID'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mic1[0m [0;34m=[0m [0mImageFileCollection[0m[0;34m([0m[0mdirectory[0m[0;34m,[0m [0mkeywords[0m[0;34m=[0m[0mkeys[0m[0;34m)[0m [0;31m# only keep track of keys[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mic1[0m[0;34m.[0m[0msummary[0m[0;34m.[0m[0mcolnames[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/ccdproc/image_collection.py[0m in [0;36m__init__[0;34m(self, location, keywords, find_fits_by_reading, filenames, glob_include, glob_exclude, ext)[0m
[1;32m    108[0m         [0mself[0m[0;34m.[0m[0m_filenames[0m [0;34m=[0m [0mfilenames[0m[0;34m[0m[0;34m[0m[0m
[1;32m    109[0m         [0mself[0m[0;34m.[0m[0m_files[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 110[0;31m         [0mself[0m[0;34m.[0m[0m_files[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_get_files[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    111[0m [0;34m[0m[0m
[1;32m    112[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0m_files[0m [0;34m==[0m [0;34m[[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/ccdproc/image_collection.py[0m in [0;36m_get_files[0;34m(self)[0m
[1;32m    449[0m                 [0mfiles[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_filenames[0m[0;34m[0m[0;34m[0m[0m
[1;32m    450[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 451[0;31m             [0mfiles[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_fits_files_in_directory[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    452[0m [0;34m[0m[0m
[1;32m    453[0m             [0;32mif[0m [0mself[0m[0;34m.[0m[0mglob_include[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/ccdproc/image_collection.py[0m in [0;36m_fits_files_in_directory[0;34m(self, extensions, compressed)[0m
[1;32m    777[0m                 [0mfull_extensions[0m[0;34m.[0m[0mextend[0m[0;34m([0m[0mwith_comp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    778[0m [0;34m[0m[0m
[0;32m--> 779[0;31m         [0mall_files[0m [0;34m=[0m [0mlistdir[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mlocation[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    780[0m         [0mfiles[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    781[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_find_fits_by_reading[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/jzamorano/Desktop/NOT_2008/N1/'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jzamorano/Desktop/NOT_2008/N1/'

